before_script:
  - apt-get update && apt-get install -y zlib1g-dev && docker-php-ext-install zip
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install --no-interaction --no-progress --prefer-dist

php7-0:
  image: php:7.0-fpm
  script:
    - composer check

php7-1:
  image: php:7.1-fpm
  script:
    - composer check

php7-2:
  image: php:7.2-fpm
  script:
    - composer check
