before_script:
- composer install

test:7.0:
  image: registry.gitlab.com/stepandalecky/kml-parser:php7-0
  script:
  - vendor/bin/phpunit tests/StepanDaleckyTests
  - vendor/bin/phpstan analyse -l 7 src tests

test:7.1:
  image: registry.gitlab.com/stepandalecky/kml-parser:php7-1
  script:
  - vendor/bin/phpunit tests/StepanDaleckyTests
  - vendor/bin/phpstan analyse -l 7 src tests
